# Generated by Django 5.2.10 on 2026-01-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FidelityTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('trade_date', models.DateField()),
                ('option_type', models.CharField(max_length=4)),
                ('strike', models.FloatField()),
                ('expiry', models.DateField()),
                ('quantity', models.IntegerField()),
                ('premium', models.FloatField()),
                ('pnl', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-trade_date', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='TradierTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('trade_date', models.DateField()),
                ('option_type', models.CharField(max_length=4)),
                ('strike', models.FloatField()),
                ('expiry', models.DateField()),
                ('quantity', models.IntegerField()),
                ('premium', models.FloatField()),
                ('pnl', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-trade_date', 'symbol'],
            },
        ),
    ]
